### ISSUE TITLE
Replicate the experiment

### ISSUE THREAD

**Issue by IAMjmj** [Sprinter1999/FedLSR#2]
Hello, in the process of reproduction, I found that there was a problem when the cifar-10 experiment was reproduced. I reproduced 66.02%, Symmetric=30%. What steps did I miss? My other parameters are the same as your code. Thank you for your answer.

**Comment by Sprinter1999** [comment]
Thank you @IAMjmj! Since I received your issue, I just go over this code and re-run your mentioned experiment for thrice, and I just get consistent results as the paper shows. There's surely some misleading information in this code. Here's some information to your issue:

- Please note that the difference between FedLSR and FedLSR+(which is mentioned in the discussion section of the paper)
- There's an underlying trade-off for us to decide whether adding the entropy regularization loss. The key motivation to add this term is to further make this model more robust to alleviate negative knowledge from noisy labels (**especially and mainly in extreme cases**), but it somehow slows down the convergence.
-  I'll complete more info in this repo.
- If possible, we can colaborate to carry on more works to tackle with this issue in FL.

Thank you again for your comments, and hope my reply can really help.

**Comment by IAMjmj** [comment]
OK, thank you for your answer. I will continue the experiment

**Comment by IAMjmj** [comment]
Of course, I am willing to work with you to solve the issue in FL, thank you for your invitation

**Comment by IAMjmj** [comment]
Thanks again for your timely reply and hope to collaborate

**Comment by IAMjmj** [comment]
Thank you for your suggestion. The gap is not so big now. Now the score is 71%, which may be due to the p100 used in the video card. Thank you again for your reply

**Comment by Sprinter1999** [comment]
> Thank you for your suggestion. The gap is not so big now. Now the score is 71%, which may be due to the p100 used in the video card. Thank you again for your reply

Huh-huh, good job! BTW, are you fighting for the CVPR 2023?

**Comment by IAMjmj** [comment]
I am preparing for my first paper. If I can win CVPR2023, I will be very happy.Thank you for your work and give me a lot of inspiration.

**Comment by Sprinter1999** [comment]
> I am preparing for my first paper. If I can win CVPR2023, I will be very happy.Thank you for your work and give me a lot of inspiration.

Got it, good luck! If you are also from China, maybe we can become Wechat friends ：）

**Comment by IAMjmj** [comment]
Yes, I'm from Chengdu. My WeChat address is 17360075977. Nice to meet you.
